function [x_ddot,y_ddot,theta_ddot,phi_ddot] = sep_accelerations(theta,phi,theta_dot,phi_dot,m1,m2,J1,J2,R,h,l,g)
%SEP_ACCELERATIONS
%    [X_DDOT,Y_DDOT,THETA_DDOT,PHI_DDOT] = SEP_ACCELERATIONS(THETA,PHI,THETA_DOT,PHI_DOT,M1,M2,J1,J2,R,H,L,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jan-2026 08:54:00

t2 = cos(theta);
t3 = sin(phi);
t4 = sin(theta);
t5 = phi+theta;
t6 = h.^2;
t7 = h.^3;
t8 = l.^2;
t9 = l.^3;
t10 = m1.^2;
t11 = m2.^2;
t12 = phi.*2.0;
t13 = phi_dot.^2;
t14 = theta_dot.^2;
t19 = -theta;
t21 = J1.*J2.*m1.*m2.*4.0;
t15 = cos(t12);
t16 = sin(t12);
t17 = cos(t5);
t18 = sin(t5);
t20 = phi+t19;
t24 = J1.*J2.*t10.*2.0;
t25 = J1.*J2.*t11.*2.0;
t26 = t12+t19;
t27 = J2.*m1.*phi_dot.*t3.*theta_dot.*4.0;
t28 = J2.*m2.*phi_dot.*t3.*theta_dot.*4.0;
t31 = J2.*m1.*t3.*t13.*2.0;
t32 = J2.*m2.*t3.*t13.*2.0;
t33 = J2.*m1.*t3.*t14.*2.0;
t34 = J2.*m2.*t3.*t14.*2.0;
t37 = J2.*m1.*t6.*t11.*2.0;
t38 = J2.*m2.*t6.*t10.*2.0;
t39 = J1.*m1.*t8.*t11.*2.0;
t40 = J1.*m2.*t8.*t10.*2.0;
t41 = m1.*m2.*phi_dot.*t3.*t8.*theta_dot.*4.0;
t42 = m1.*m2.*t3.*t8.*t13.*2.0;
t43 = m1.*m2.*t3.*t8.*t14.*2.0;
t45 = t6.*t8.*t10.*t11;
t22 = cos(t20);
t23 = sin(t20);
t29 = cos(t26);
t30 = sin(t26);
t35 = -t27;
t36 = -t28;
t44 = -t41;
t46 = t15.*t45;
t47 = -t46;
t48 = t21+t24+t25+t37+t38+t39+t40+t45+t47;
t49 = 1.0./t48;
et1 = h.*t4.*t14.*t24+h.*t4.*t14.*t40+l.*phi_dot.*t21.*t23.*theta_dot+l.*phi_dot.*t18.*t38.*theta_dot+l.*phi_dot.*t23.*t38.*theta_dot+t4.*t7.*t8.*t10.*t11.*t14-t6.*t9.*t10.*t11.*t13.*t18-t6.*t9.*t10.*t11.*t14.*t18-t6.*t9.*t10.*t11.*t13.*t23-t6.*t9.*t10.*t11.*t14.*t23+t7.*t8.*t10.*t11.*t14.*t30-J1.*J2.*l.*t11.*t13.*t23.*2.0-J1.*J2.*l.*t11.*t14.*t23.*2.0+J2.*m2.*t4.*t7.*t10.*t14.*2.0-J1.*m1.*t9.*t11.*t13.*t23.*2.0-J1.*m1.*t9.*t11.*t14.*t23.*2.0+J1.*J2.*h.*m1.*m2.*t4.*t14.*2.0-J1.*J2.*l.*m1.*m2.*t13.*t23.*2.0-J1.*J2.*l.*m1.*m2.*t14.*t23.*2.0+J1.*J2.*l.*phi_dot.*t11.*t23.*theta_dot.*4.0+J1.*h.*m1.*t4.*t8.*t11.*t14+J1.*h.*m1.*t8.*t11.*t14.*t30-J2.*l.*m2.*t6.*t10.*t13.*t18-J2.*l.*m2.*t6.*t10.*t14.*t18;
et2 = J2.*l.*m1.*t6.*t11.*t13.*t23.*-2.0-J2.*l.*m2.*t6.*t10.*t13.*t23-J2.*l.*m1.*t6.*t11.*t14.*t23.*2.0-J2.*l.*m2.*t6.*t10.*t14.*t23+J1.*m1.*phi_dot.*t9.*t11.*t23.*theta_dot.*4.0+phi_dot.*t6.*t9.*t10.*t11.*t18.*theta_dot.*2.0+phi_dot.*t6.*t9.*t10.*t11.*t23.*theta_dot.*2.0+J2.*l.*m1.*phi_dot.*t6.*t11.*t23.*theta_dot.*4.0;
x_ddot = t49.*(et1+et2);
if nargout > 1
    et3 = g.*t21+g.*t24+g.*t25+g.*t37+g.*t38+g.*t39+g.*t40+g.*t45+g.*t47+h.*t2.*t14.*t24+h.*t2.*t14.*t40+l.*t13.*t22.*t25+l.*t14.*t22.*t25+l.*t13.*t22.*t37+l.*t14.*t22.*t37+l.*phi_dot.*t17.*t38.*theta_dot+t2.*t7.*t8.*t10.*t11.*t14-t6.*t9.*t10.*t11.*t13.*t17-t6.*t9.*t10.*t11.*t14.*t17+t6.*t9.*t10.*t11.*t13.*t22+t6.*t9.*t10.*t11.*t14.*t22-t7.*t8.*t10.*t11.*t14.*t29+J2.*m2.*t2.*t7.*t10.*t14.*2.0+J1.*m1.*t9.*t11.*t13.*t22.*2.0+J1.*m1.*t9.*t11.*t14.*t22.*2.0+J1.*J2.*h.*m1.*m2.*t2.*t14.*2.0+J1.*J2.*l.*m1.*m2.*t13.*t22.*2.0+J1.*J2.*l.*m1.*m2.*t14.*t22.*2.0-J1.*J2.*l.*phi_dot.*t11.*t22.*theta_dot.*4.0+J1.*h.*m1.*t2.*t8.*t11.*t14-J1.*h.*m1.*t8.*t11.*t14.*t29-J2.*l.*m2.*t6.*t10.*t13.*t17;
    et4 = -J2.*l.*m2.*t6.*t10.*t14.*t17+J2.*l.*m2.*t6.*t10.*t13.*t22+J2.*l.*m2.*t6.*t10.*t14.*t22-J1.*m1.*phi_dot.*t9.*t11.*t22.*theta_dot.*4.0+phi_dot.*t6.*t9.*t10.*t11.*t17.*theta_dot.*2.0-phi_dot.*t6.*t9.*t10.*t11.*t22.*theta_dot.*2.0-J1.*J2.*l.*m1.*m2.*phi_dot.*t22.*theta_dot.*4.0-J2.*l.*m1.*phi_dot.*t6.*t11.*t22.*theta_dot.*4.0-J2.*l.*m2.*phi_dot.*t6.*t10.*t22.*theta_dot.*2.0;
    y_ddot = -t49.*(et3+et4);
end
if nargout > 2
    theta_ddot = (h.*l.*m1.*m2.*(t31+t32+t33+t34+t35+t36+t42+t43+t44-h.*l.*m1.*m2.*t14.*t16))./(t45.*2.0-t45.*cos(phi).^2.*2.0+J1.*J2.*t10.*2.0+J1.*J2.*t11.*2.0+J1.*J2.*m1.*m2.*4.0+J2.*m1.*t6.*t11.*2.0+J2.*m2.*t6.*t10.*2.0+J1.*m1.*t8.*t11.*2.0+J1.*m2.*t8.*t10.*2.0);
end
if nargout > 3
    phi_ddot = h.*l.*m1.*m2.*t49.*(t31+t32+t33+t34+t35+t36+t42+t43+t44+J1.*m1.*t3.*t14.*2.0+J1.*m2.*t3.*t14.*2.0+m1.*m2.*t3.*t6.*t14.*2.0-h.*l.*m1.*m2.*t13.*t16-h.*l.*m1.*m2.*t14.*t16.*2.0+h.*l.*m1.*m2.*phi_dot.*t16.*theta_dot.*2.0);
end
end
