function [theta_ddot,phi_ddot] = stick_accelerations(theta,phi,theta_dot,phi_dot,m1,m2,J1,J2,R,h,l,g)
%STICK_ACCELERATIONS
%    [THETA_DDOT,PHI_DDOT] = STICK_ACCELERATIONS(THETA,PHI,THETA_DOT,PHI_DOT,M1,M2,J1,J2,R,H,L,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    16-Jan-2026 18:20:29

t2 = cos(theta);
t3 = sin(phi);
t4 = sin(theta);
t5 = R.^2;
t6 = h.^2;
t7 = l.^2;
t8 = l.^3;
t9 = m2.^2;
t10 = phi.*2.0;
t11 = phi_dot.^2;
t12 = theta.*2.0;
t13 = theta_dot.^2;
t14 = -theta;
t15 = -t12;
t16 = phi+t14;
t22 = t5.*t7.*t9;
t17 = phi+t15;
t18 = sin(t16);
t20 = t10+t15;
t19 = sin(t17);
t21 = sin(t20);
theta_ddot = -(J2.*g.*h.*m1.*t4-(R.*g.*t7.*t9.*t21)./2.0-R.*t8.*t9.*t11.*t18-R.*t8.*t9.*t13.*t18+J2.*R.*h.*m1.*t4.*t13-J2.*R.*l.*m2.*t11.*t18-J2.*R.*l.*m2.*t13.*t18+g.*h.*m1.*m2.*t4.*t7+R.*phi_dot.*t8.*t9.*t18.*theta_dot.*2.0+J2.*R.*l.*m2.*phi_dot.*t18.*theta_dot.*2.0+R.*h.*m1.*m2.*t4.*t7.*t13)./(t22-t22.*cos(t16).^2+J1.*J2+J2.*m1.*t5+J2.*m1.*t6+J2.*m2.*t5+J1.*m2.*t7+m1.*m2.*t5.*t7+m1.*m2.*t6.*t7-J2.*R.*h.*m1.*t2.*2.0-R.*h.*m1.*m2.*t2.*t7.*2.0);
if nargout > 1
    et1 = 1.0./(t22-t22.*cos(t20)+J1.*J2.*2.0+J2.*m1.*t5.*2.0+J2.*m1.*t6.*2.0+J2.*m2.*t5.*2.0+J1.*m2.*t7.*2.0+m1.*m2.*t5.*t7.*2.0+m1.*m2.*t6.*t7.*2.0-J2.*R.*h.*m1.*t2.*4.0-R.*h.*m1.*m2.*t2.*t7.*4.0);
    et2 = -(t11.*t21.*t22+t13.*t21.*t22-phi_dot.*t21.*t22.*theta_dot.*2.0+J2.*g.*h.*m1.*t4.*2.0+J1.*g.*l.*m2.*t18.*2.0-R.*g.*t7.*t9.*t21-R.*t8.*t9.*t11.*t18.*2.0-R.*t8.*t9.*t13.*t18.*2.0+g.*l.*t5.*t9.*t18.*2.0+J2.*R.*h.*m1.*t4.*t13.*2.0-J2.*R.*l.*m2.*t11.*t18.*2.0-J2.*R.*l.*m2.*t13.*t18.*2.0+g.*h.*m1.*m2.*t4.*t7.*2.0+R.*phi_dot.*t8.*t9.*t18.*theta_dot.*4.0+g.*l.*m1.*m2.*t5.*t18.*2.0+g.*l.*m1.*m2.*t6.*t18.*2.0+J2.*R.*l.*m2.*phi_dot.*t18.*theta_dot.*4.0-R.*g.*h.*l.*m1.*m2.*t3.*3.0-R.*g.*h.*l.*m1.*m2.*t19+R.*h.*m1.*m2.*t4.*t7.*t13.*2.0-h.*l.*m1.*m2.*t3.*t5.*t13+h.*l.*m1.*m2.*t5.*t13.*t19);
    phi_ddot = et1.*et2;
end
end
