function [lambda_n,lambda_t] = stick_forces(theta,phi,theta_dot,phi_dot,m1,m2,J1,J2,R,h,l,g)
%STICK_FORCES
%    [LAMBDA_N,LAMBDA_T] = STICK_FORCES(THETA,PHI,THETA_DOT,PHI_DOT,M1,M2,J1,J2,R,H,L,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Jan-2026 08:53:59

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(theta);
t5 = R.^2;
t6 = h.^2;
t7 = h.^3;
t8 = l.^2;
t9 = l.^3;
t10 = m1.^2;
t11 = m2.^2;
t12 = phi.*2.0;
t13 = phi_dot.^2;
t14 = theta.*2.0;
t15 = theta_dot.^2;
t18 = -theta;
t16 = cos(t14);
t17 = sin(t14);
t19 = -t14;
t20 = phi+t18;
t25 = t12+t18;
t31 = t5.*t8.*t11;
t21 = phi+t19;
t22 = cos(t20);
t24 = sin(t20);
t26 = t12+t19;
t27 = cos(t25);
t23 = cos(t21);
t28 = cos(t26);
et1 = g.*m1.*t31.*2.0+J1.*J2.*g.*m1.*2.0+J1.*J2.*g.*m2.*2.0+J2.*g.*t5.*t10.*2.0+J2.*g.*t5.*t11.*2.0+J2.*g.*t6.*t10+J1.*g.*t8.*t11-J2.*R.*t6.*t10.*t15.*3.0+J2.*g.*m1.*m2.*t5.*4.0+J2.*g.*m1.*m2.*t6.*2.0+J1.*g.*m1.*m2.*t8.*2.0+J2.*g.*t6.*t10.*t16+J1.*g.*t8.*t11.*t28+J2.*t3.*t7.*t10.*t15.*2.0+J1.*t9.*t11.*t13.*t22.*2.0+J1.*t9.*t11.*t15.*t22.*2.0+g.*m2.*t5.*t8.*t10.*2.0+g.*m1.*t6.*t8.*t11+g.*m2.*t6.*t8.*t10+h.*m1.*t3.*t15.*t31-h.*m1.*t15.*t27.*t31+g.*m2.*t6.*t8.*t10.*t16+g.*m1.*t6.*t8.*t11.*t28+m2.*t3.*t7.*t8.*t10.*t15.*2.0+m1.*t5.*t9.*t11.*t13.*t22.*2.0+m1.*t6.*t9.*t11.*t13.*t22.*2.0+m1.*t5.*t9.*t11.*t15.*t22.*2.0+m1.*t6.*t9.*t11.*t15.*t22.*2.0+J1.*J2.*h.*m1.*t3.*t15.*2.0;
et2 = J2.*R.*g.*h.*t3.*t10.*-4.0+J1.*J2.*l.*m2.*t13.*t22.*2.0+J1.*J2.*l.*m2.*t15.*t22.*2.0-J2.*R.*t6.*t10.*t15.*t16+J2.*h.*t3.*t5.*t10.*t15.*2.0+J2.*l.*t5.*t11.*t13.*t22.*2.0+J2.*l.*t5.*t11.*t15.*t22.*2.0-J1.*phi_dot.*t9.*t11.*t22.*theta_dot.*4.0-R.*m2.*t6.*t8.*t10.*t15.*3.0-J2.*R.*g.*h.*m1.*m2.*t3.*4.0-J1.*J2.*l.*m2.*phi_dot.*t22.*theta_dot.*4.0+J2.*h.*m1.*m2.*t3.*t5.*t15.*2.0+J1.*h.*m1.*m2.*t3.*t8.*t15.*2.0-R.*g.*h.*m1.*t3.*t8.*t11.*2.0-R.*g.*h.*m2.*t3.*t8.*t10.*4.0-R.*g.*h.*m1.*t8.*t11.*t27.*2.0+J2.*l.*m1.*m2.*t5.*t13.*t22.*2.0+J2.*l.*m1.*m2.*t6.*t13.*t22.*2.0+J2.*l.*m1.*m2.*t5.*t15.*t22.*2.0+J2.*l.*m1.*m2.*t6.*t15.*t22.*2.0-J2.*l.*phi_dot.*t5.*t11.*t22.*theta_dot.*4.0-R.*h.*m1.*t2.*t9.*t11.*t13.*3.0;
et3 = R.*h.*m1.*t2.*t9.*t11.*t15.*-3.0-R.*h.*m1.*t9.*t11.*t13.*t23-R.*h.*m1.*t9.*t11.*t15.*t23-R.*m2.*t6.*t8.*t10.*t15.*t16+h.*m2.*t3.*t5.*t8.*t10.*t15.*2.0-m1.*phi_dot.*t5.*t9.*t11.*t22.*theta_dot.*4.0-m1.*phi_dot.*t6.*t9.*t11.*t22.*theta_dot.*4.0-J2.*R.*h.*l.*m1.*m2.*t2.*t13.*3.0-J2.*R.*h.*l.*m1.*m2.*t2.*t15.*3.0-J2.*R.*h.*l.*m1.*m2.*t13.*t23-J2.*R.*h.*l.*m1.*m2.*t15.*t23-J2.*l.*m1.*m2.*phi_dot.*t5.*t22.*theta_dot.*4.0-J2.*l.*m1.*m2.*phi_dot.*t6.*t22.*theta_dot.*4.0+R.*h.*m1.*phi_dot.*t2.*t9.*t11.*theta_dot.*6.0+R.*h.*m1.*phi_dot.*t9.*t11.*t23.*theta_dot.*2.0+J2.*R.*h.*l.*m1.*m2.*phi_dot.*t2.*theta_dot.*6.0+J2.*R.*h.*l.*m1.*m2.*phi_dot.*t23.*theta_dot.*2.0;
lambda_n = (et1+et2+et3)./(t31-t28.*t31+J1.*J2.*2.0+J2.*m1.*t5.*2.0+J2.*m1.*t6.*2.0+J2.*m2.*t5.*2.0+J1.*m2.*t8.*2.0+m1.*m2.*t5.*t8.*2.0+m1.*m2.*t6.*t8.*2.0-J2.*R.*h.*m1.*t3.*4.0-R.*h.*m1.*m2.*t3.*t8.*4.0);
if nargout > 1
    t29 = t22.^2;
    t30 = sin(t26);
    et4 = J2.*g.*t6.*t10.*t17.*(-1.0./2.0)+(J1.*g.*t8.*t11.*t30)./2.0-J2.*t4.*t7.*t10.*t15+J1.*t9.*t11.*t13.*t24+J1.*t9.*t11.*t15.*t24-(g.*m2.*t6.*t8.*t10.*t17)./2.0+(g.*m1.*t6.*t8.*t11.*t30)./2.0-m2.*t4.*t7.*t8.*t10.*t15+m1.*t6.*t9.*t11.*t13.*t24+m1.*t6.*t9.*t11.*t15.*t24-J1.*J2.*h.*m1.*t4.*t15+J2.*R.*g.*h.*t4.*t10+J1.*J2.*l.*m2.*t13.*t24+J1.*J2.*l.*m2.*t15.*t24+(J2.*R.*t6.*t10.*t15.*t17)./2.0-J1.*phi_dot.*t9.*t11.*t24.*theta_dot.*2.0+J2.*R.*g.*h.*m1.*m2.*t4-J1.*J2.*l.*m2.*phi_dot.*t24.*theta_dot.*2.0-J1.*h.*m1.*m2.*t4.*t8.*t15+R.*g.*h.*m1.*t4.*t8.*t11+R.*g.*h.*m2.*t4.*t8.*t10+J2.*l.*m1.*m2.*t6.*t13.*t24+J2.*l.*m1.*m2.*t6.*t15.*t24;
    et5 = (R.*m2.*t6.*t8.*t10.*t15.*t17)./2.0-m1.*phi_dot.*t6.*t9.*t11.*t24.*theta_dot.*2.0-R.*g.*h.*m1.*t8.*t11.*(sin(t12-theta.*3.0)./4.0+sin(t25)./4.0)-J2.*l.*m1.*m2.*phi_dot.*t6.*t24.*theta_dot.*2.0-R.*g.*h.*m1.*t4.*t8.*t11.*t29-R.*h.*m1.*t3.*t9.*t11.*t13.*t24-R.*h.*m1.*t3.*t9.*t11.*t15.*t24-J2.*R.*h.*l.*m1.*m2.*t3.*t13.*t24-J2.*R.*h.*l.*m1.*m2.*t3.*t15.*t24+R.*h.*m1.*phi_dot.*t3.*t9.*t11.*t24.*theta_dot.*2.0+J2.*R.*h.*l.*m1.*m2.*phi_dot.*t3.*t24.*theta_dot.*2.0;
    lambda_t = (et4+et5)./(t31-t29.*t31+J1.*J2+J2.*m1.*t5+J2.*m1.*t6+J2.*m2.*t5+J1.*m2.*t8+m1.*m2.*t5.*t8+m1.*m2.*t6.*t8-J2.*R.*h.*m1.*t3.*2.0-R.*h.*m1.*m2.*t3.*t8.*2.0);
end
end
