function A_c = collision_matrix(theta_c,m,m_h,I_c,l)
%COLLISION_MATRIX
%    A_c = COLLISION_MATRIX(THETA_C,M,M_H,I_c,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:40

t2 = sin(theta_c);
t3 = I_c.*m_h;
t4 = m+m_h;
t5 = I_c.^2;
t6 = l.^2;
t8 = m.^2;
t9 = m.^3;
t11 = m_h.^2;
t12 = theta_c.*2.0;
t13 = I_c.*m.*2.0;
t7 = t6.^2;
t10 = t8.^2;
t14 = cos(t12);
t15 = sin(t12);
t16 = t2.^2;
t17 = I_c.*t3;
t18 = m.*m_h.*t6;
t19 = m.*t5.*2.0;
t22 = t3.^2;
t24 = t6.*t8;
t26 = t5.*t8.*4.0;
t27 = I_c.*t6.*t9.*4.0;
t20 = t14.^2;
t21 = t15.^2;
t23 = m.*t17.*4.0;
t25 = t7.*t10;
t28 = m_h.*t7.*t9.*2.0;
t29 = t3.*t18.*2.0;
t30 = t3.*t24.*6.0;
t31 = t7.*t8.*t11;
t33 = t3+t13+t18+t24;
t32 = t21.*t25;
t34 = t22+t23+t26+t27+t28+t29+t30+t31+t32;
t35 = 1.0./t34;
t36 = t4.*t6.*t15.*t33.*t35.*2.0;
mt1 = [(t17+t19+I_c.*t24.*7.0+t7.*t9.*3.0+I_c.*t14.*t24.*5.0+m.*t3.*t6.*8.0+m.*t7.*t11.*2.0+m_h.*t3.*t6.*2.0+m_h.*t7.*t8.*5.0+t7.*t9.*t14-t7.*t9.*t20.*2.0+m.*t3.*t6.*t14.*6.0+m.*t7.*t11.*t14.*2.0+m_h.*t3.*t6.*t14.*2.0+m_h.*t7.*t8.*t14.*4.0)./(t22+t23+t25+t26+t27+t28+t29+t30+t31-t20.*t25),t36,t36];
mt2 = [((t17+t19+I_c.*t24.*2.0-t7.*t9.*t16.^2.*8.0+I_c.*t16.*t24.*1.0e+1+m.*t3.*t6.*2.0+m_h.*t7.*t8+t7.*t9.*t16.*1.0e+1+m.*t3.*t6.*t16.*1.2e+1+m.*t7.*t11.*t16.*4.0+m_h.*t3.*t6.*t16.*4.0+m_h.*t7.*t8.*t16.*8.0).*2.0)./(t22.*2.0+t25+t31.*2.0-t25.*cos(theta_c.*4.0)+m.*t17.*8.0+t5.*t8.*8.0+t3.*t18.*4.0+t3.*t24.*1.2e+1+I_c.*t6.*t9.*8.0+m_h.*t7.*t9.*4.0)];
A_c = reshape([mt1,mt2],2,2);
end
