function B = coriolis_vector(theta1,theta2,theta1_dot,theta2_dot,m,m_h,l)
%CORIOLIS_VECTOR
%    B = CORIOLIS_VECTOR(THETA1,THETA2,THETA1_DOT,THETA2_DOT,M,M_H,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:34

t2 = theta1+theta2;
t3 = l.^2;
t4 = m.*3.0;
t5 = m_h.*2.0;
t6 = theta1_dot.^2;
t7 = theta2_dot.^2;
t8 = sin(t2);
t9 = t4+t5;
B = [-l.*m.*t7.*sin(theta2)-l.*t6.*t9.*sin(theta1);l.*m.*t7.*cos(theta2)-l.*t6.*t9.*cos(theta1);m.*t3.*t7.*t8.*-2.0;m.*t3.*t6.*t8.*-2.0];
end
