function G = gravity_vector(theta1,theta2,m,m_h,l,g,alpha)
%GRAVITY_VECTOR
%    G = GRAVITY_VECTOR(THETA1,THETA2,M,M_H,L,g,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:34

t2 = m.*2.0;
t3 = m_h+t2;
G = [-g.*t3.*sin(alpha);g.*t3.*cos(alpha);-g.*l.*sin(alpha+theta1).*(m.*3.0+m_h.*2.0);-g.*l.*m.*sin(alpha-theta2)];
end
