function M_inv_W_T = impulse_to_velocity(theta_c,m,m_h,I_c,l)
%IMPULSE_TO_VELOCITY
%    M_inv_W_T = IMPULSE_TO_VELOCITY(THETA_C,M,M_H,I_c,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:40

t2 = cos(theta_c);
t3 = sin(theta_c);
t4 = m+m_h;
t5 = I_c.^2;
t6 = l.^2;
t8 = m.^2;
t9 = m.^3;
t11 = m_h.^2;
t12 = theta_c.*2.0;
t13 = theta_c.*3.0;
t14 = theta_c.*4.0;
t21 = I_c.*m.*m_h.*7.0;
t7 = t6.^2;
t10 = t8.^2;
t15 = cos(t12);
t16 = cos(t13);
t17 = cos(t14);
t18 = sin(t13);
t19 = sin(t14);
t20 = m_h.*t5;
t22 = m.*t5.*2.0;
t23 = I_c.*t8.*6.0;
t24 = I_c.*t11.*2.0;
t26 = I_c.*t6.*t8;
t27 = t5.*t11.*2.0;
t29 = t6.*t9.*4.0;
t30 = m.*t6.*t11.*2.0;
t31 = m_h.*t6.*t8.*5.0;
t33 = t5.*t8.*8.0;
t35 = I_c.*t6.*t9.*8.0;
t36 = I_c.*m.*t6.*t11.*4.0;
t25 = t7.*t10;
t28 = m.*t20.*8.0;
t32 = m_h.*t7.*t9.*4.0;
t34 = -t26;
t37 = t7.*t9.*t15;
t38 = t7.*t9.*t17;
t40 = m_h.*t26.*1.2e+1;
t41 = t7.*t8.*t11.*2.0;
t42 = I_c.*m.*m_h.*t6.*t15.*2.0;
t43 = m_h.*t7.*t8.*t17;
t45 = t15.*t26.*3.0;
t39 = t17.*t25;
t44 = -t39;
t46 = t25+t27+t28+t32+t33+t35+t36+t40+t41+t44;
t47 = 1.0./t46;
t48 = t4.*t7.*t8.*t19.*t47.*2.0;
M_inv_W_T = reshape([t47.*(t20+t22+t34+t37+t38-t42+t43-t45).*2.0,-t48,-l.*m.*t47.*(I_c.*m.*t2.*-4.0-I_c.*m_h.*t2.*2.0+t2.*t6.*t8+t6.*t8.*t16.*3.0+m.*m_h.*t6.*t16.*2.0),l.*t2.*t47.*(t21+t23+t24+t29+t30+t31-t2.^2.*t6.*t9.*2.0).*2.0,t48,t47.*(t20+t22+t34-t37+t38+t42+t43+t45).*2.0,-l.*m.*t47.*(I_c.*m.*t3.*4.0+I_c.*m_h.*t3.*2.0-t3.*t6.*t8+t6.*t8.*t18.*3.0+m.*m_h.*t6.*t18.*2.0),l.*t3.*t47.*(t21+t23+t24+t29+t30+t31-t3.^2.*t6.*t9.*2.0).*2.0],[4,2]);
end
