function M = mass_matrix(theta1,theta2,m,m_h,I_c,l)
%MASS_MATRIX
%    M = MASS_MATRIX(THETA1,THETA2,m,M_H,I_c,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:34

t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = theta1+theta2;
t7 = l.^2;
t8 = m.*2.0;
t9 = m.*3.0;
t10 = m_h.*2.0;
t11 = cos(t6);
t12 = l.*m.*t3;
t13 = l.*m.*t5;
t14 = m_h+t8;
t15 = t9+t10;
t16 = t7.*t8.*t11;
t17 = l.*t2.*t15;
t18 = l.*t4.*t15;
t19 = -t18;
M = reshape([t14,0.0,t17,t12,0.0,t14,t19,t13,t17,t19,I_c+m.*t7.*5.0+m_h.*t7.*4.0,t16,t12,t13,t16,I_c+m.*t7],[4,4]);
end
