function [x_ddot,theta1_ddot,theta2_ddot,lambda_n] = slip_accelerations(theta1,theta2,x_dot,theta1_dot,theta2_dot,m,m_h,I_c,l,g,alpha,mu,sigma)
%SLIP_ACCELERATIONS
%    [X_DDOT,THETA1_DDOT,THETA2_DDOT,LAMBDA_N] = SLIP_ACCELERATIONS(THETA1,THETA2,X_DOT,THETA1_DOT,THETA2_DOT,M,M_H,I_c,L,G,ALPHA,MU,SIGMA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:39

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(theta1);
t5 = cos(theta2);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = I_c.^2;
t9 = l.^2;
t10 = l.^3;
t12 = l.^5;
t13 = m.^2;
t14 = m.^3;
t16 = m_h.^2;
t17 = theta1.*2.0;
t18 = theta2.*2.0;
t19 = theta1_dot.^2;
t20 = theta2_dot.^2;
t27 = -alpha;
t11 = t9.^2;
t15 = t13.^2;
t21 = cos(t17);
t22 = cos(t18);
t23 = t4.^2;
t24 = t5.^2;
t25 = sin(t17);
t26 = sin(t18);
t28 = -t18;
t29 = alpha+t17;
t30 = t18+theta1;
t31 = t17+theta2;
t37 = m.*t8.*4.0;
t38 = m_h.*t8.*2.0;
t41 = t17+t18;
t47 = I_c.*t9.*t16.*4.0;
t48 = I_c.*m.*m_h.*t9.*1.6e+1;
t51 = I_c.*t9.*t13.*1.4e+1;
t32 = sin(t29);
t33 = cos(t30);
t34 = cos(t31);
t35 = sin(t30);
t36 = sin(t31);
t39 = alpha+t28;
t40 = cos(t29);
t44 = t18+t29;
t45 = cos(t41);
t46 = t11.*t14.*4.0;
t49 = m.*t11.*t16.*4.0;
t52 = m_h.*t11.*t13.*1.0e+1;
t53 = t11.*t14.*t22;
t54 = t27+t41;
t56 = t11.*t14.*t21.*3.0;
t57 = I_c.*t9.*t13.*t22;
t58 = mu.*sigma.*t11.*t14.*t26;
t61 = I_c.*m.*m_h.*t9.*t21.*1.2e+1;
t63 = mu.*sigma.*t11.*t14.*t25.*3.0;
t64 = I_c.*mu.*sigma.*t9.*t13.*t26;
t66 = I_c.*t9.*t13.*t21.*9.0;
t67 = I_c.*t9.*t16.*t21.*-4.0;
t69 = m.*t11.*t16.*t21.*-4.0;
t70 = m_h.*t11.*t13.*t21.*8.0;
t71 = mu.*sigma.*t25.*t47;
t72 = I_c.*m.*m_h.*mu.*sigma.*t9.*t25.*1.2e+1;
t78 = I_c.*mu.*sigma.*t9.*t13.*t25.*9.0;
t79 = m_h.*mu.*sigma.*t11.*t13.*t25.*8.0;
t42 = sin(t39);
t43 = cos(t39);
t50 = cos(t44);
t55 = cos(t54);
t59 = -t56;
t65 = -t57;
t68 = -t61;
t73 = -t66;
t74 = mu.*sigma.*t25.*t49;
t75 = -t70;
t76 = t11.*t14.*t45.*2.0;
t77 = -t64;
t80 = -t76;
t81 = t37+t38+t46+t47+t48+t49+t51+t52+t53+t58+t59+t63+t65+t67+t68+t69+t71+t72+t73+t74+t75+t77+t78+t79+t80;
t82 = 1.0./t81;
et1 = g.*t32.*t47+g.*t32.*t49-g.*m.*t3.*t8.*4.0-g.*m_h.*t3.*t8.*2.0-g.*t3.*t11.*t14.*4.0+g.*t11.*t14.*t32.*3.0-g.*t11.*t14.*t42-t6.*t12.*t14.*t19.*8.0-t12.*t14.*t19.*t35.*2.0+t12.*t14.*t20.*t36.*2.0+g.*t11.*t14.*sin(t44)-g.*t11.*t14.*sin(t54)-I_c.*g.*t3.*t9.*t13.*1.4e+1-I_c.*g.*t3.*t9.*t16.*4.0+I_c.*g.*t9.*t13.*t32.*9.0+I_c.*g.*t9.*t13.*t42-I_c.*t6.*t10.*t13.*t19.*3.4e+1-I_c.*t7.*t10.*t13.*t20.*6.0-I_c.*t6.*t10.*t16.*t19.*1.6e+1+I_c.*t10.*t13.*t19.*t35.*2.0+I_c.*t10.*t13.*t20.*t36.*6.0+g.*mu.*sigma.*t2.*t37+g.*mu.*sigma.*t2.*t38+g.*mu.*sigma.*t2.*t46+g.*mu.*sigma.*t2.*t47+g.*mu.*sigma.*t2.*t48+g.*mu.*sigma.*t2.*t49+g.*mu.*sigma.*t2.*t51+g.*mu.*sigma.*t2.*t52;
et2 = g.*mu.*sigma.*t40.*t47+g.*mu.*sigma.*t40.*t49-g.*m.*t3.*t11.*t16.*4.0-g.*m_h.*t3.*t11.*t13.*1.0e+1+g.*m_h.*t11.*t13.*t32.*8.0-l.*m.*t6.*t8.*t19.*6.0-l.*m.*t7.*t8.*t20.*2.0-l.*m_h.*t6.*t8.*t19.*4.0-m.*t6.*t12.*t16.*t19.*1.6e+1-m_h.*t6.*t12.*t13.*t19.*2.8e+1-m_h.*t7.*t12.*t13.*t20.*4.0+m_h.*t12.*t13.*t20.*t36.*4.0+g.*mu.*sigma.*t11.*t14.*t40.*3.0-g.*mu.*sigma.*t11.*t14.*t43-g.*mu.*sigma.*t11.*t14.*t50-g.*mu.*sigma.*t11.*t14.*t55-mu.*sigma.*t4.*t12.*t14.*t19.*8.0+mu.*sigma.*t12.*t14.*t19.*t33.*2.0+mu.*sigma.*t12.*t14.*t20.*t34.*2.0-I_c.*g.*m.*m_h.*t3.*t9.*1.6e+1+I_c.*g.*m.*m_h.*t9.*t32.*1.2e+1-I_c.*m.*m_h.*t6.*t10.*t19.*4.8e+1-I_c.*m.*m_h.*t7.*t10.*t20.*4.0;
et3 = I_c.*m.*m_h.*t10.*t20.*t36.*4.0+I_c.*g.*mu.*sigma.*t9.*t13.*t40.*9.0+I_c.*g.*mu.*sigma.*t9.*t13.*t43-I_c.*mu.*sigma.*t4.*t10.*t13.*t19.*3.4e+1+I_c.*mu.*sigma.*t5.*t10.*t13.*t20.*6.0-I_c.*mu.*sigma.*t4.*t10.*t16.*t19.*1.6e+1-I_c.*mu.*sigma.*t10.*t13.*t19.*t33.*2.0+I_c.*mu.*sigma.*t10.*t13.*t20.*t34.*6.0+g.*m_h.*mu.*sigma.*t11.*t13.*t40.*8.0-l.*m.*mu.*sigma.*t4.*t8.*t19.*6.0+l.*m.*mu.*sigma.*t5.*t8.*t20.*2.0-l.*m_h.*mu.*sigma.*t4.*t8.*t19.*4.0-m.*mu.*sigma.*t4.*t12.*t16.*t19.*1.6e+1-m_h.*mu.*sigma.*t4.*t12.*t13.*t19.*2.8e+1+m_h.*mu.*sigma.*t5.*t12.*t13.*t20.*4.0+m_h.*mu.*sigma.*t12.*t13.*t20.*t34.*4.0+I_c.*g.*m.*m_h.*mu.*sigma.*t9.*t40.*1.2e+1-I_c.*m.*m_h.*mu.*sigma.*t4.*t10.*t19.*4.8e+1+I_c.*m.*m_h.*mu.*sigma.*t5.*t10.*t20.*4.0+I_c.*m.*m_h.*mu.*sigma.*t10.*t20.*t34.*4.0;
x_ddot = -t82.*(et1+et2+et3);
if nargout > 1
    et4 = t11.*t14.*t19.*t25.*(-1.0./2.0)+t11.*t14.*t19.*t26-I_c.*t9.*t13.*t19.*t25.*(9.0./2.0)-I_c.*t9.*t16.*t19.*t25.*2.0+g.*t2.*t6.*t10.*t14.*2.0-m.*t11.*t16.*t19.*t25.*2.0-m_h.*t11.*t13.*t19.*t25.*4.0+t4.*t7.*t11.*t14.*t20+t5.*t6.*t11.*t14.*t20.*2.0+g.*m.*t2.*t6.*t10.*t16.*2.0+g.*m_h.*t2.*t6.*t10.*t13.*5.0+g.*t2.*t6.*t10.*t14.*t24-mu.*sigma.*t11.*t14.*t19.*t23.*3.0+m_h.*t5.*t6.*t11.*t13.*t20.*2.0-t4.*t6.*t11.*t14.*t19.*t24.*4.0-t5.*t7.*t11.*t14.*t19.*t23.*4.0+I_c.*g.*l.*t2.*t6.*t13.*6.0+I_c.*g.*l.*t2.*t6.*t16.*2.0-I_c.*m.*m_h.*t9.*t19.*t25.*6.0+I_c.*t4.*t7.*t9.*t13.*t20+I_c.*t5.*t6.*t9.*t13.*t20.*4.0+I_c.*g.*l.*m.*m_h.*t2.*t6.*7.0+I_c.*m.*m_h.*t5.*t6.*t9.*t20.*2.0-I_c.*mu.*sigma.*t9.*t13.*t19.*t23.*9.0;
    et5 = I_c.*mu.*sigma.*t9.*t16.*t19.*t23.*-4.0+g.*mu.*sigma.*t2.*t4.*t10.*t14.*3.0-m.*mu.*sigma.*t11.*t16.*t19.*t23.*4.0-m_h.*mu.*sigma.*t11.*t13.*t19.*t23.*8.0+g.*t2.*t4.*t5.*t7.*t10.*t14+mu.*sigma.*t4.*t5.*t11.*t14.*t20+I_c.*g.*l.*mu.*sigma.*t2.*t4.*t13.*6.0+I_c.*g.*l.*mu.*sigma.*t2.*t4.*t16.*2.0-I_c.*m.*m_h.*mu.*sigma.*t9.*t19.*t23.*1.2e+1+I_c.*mu.*sigma.*t4.*t5.*t9.*t13.*t20.*3.0+g.*m.*mu.*sigma.*t2.*t4.*t10.*t16.*2.0+g.*m_h.*mu.*sigma.*t2.*t4.*t10.*t13.*5.0-g.*mu.*sigma.*t2.*t4.*t10.*t14.*t24+m_h.*mu.*sigma.*t4.*t5.*t11.*t13.*t20.*2.0+I_c.*g.*l.*m.*m_h.*mu.*sigma.*t2.*t4.*7.0+I_c.*m.*m_h.*mu.*sigma.*t4.*t5.*t9.*t20.*2.0+g.*mu.*sigma.*t2.*t5.*t6.*t7.*t10.*t14;
    theta1_ddot = t82.*(et4+et5).*2.0;
end
if nargout > 2
    et6 = t11.*t14.*t20.*t25+t11.*t14.*t20.*t26.*(3.0./2.0)-(I_c.*t9.*t13.*t20.*t26)./2.0+g.*t2.*t7.*t10.*t14.*2.0+t4.*t7.*t11.*t14.*t19.*2.0+t5.*t6.*t11.*t14.*t19.*5.0+g.*m_h.*t2.*t7.*t10.*t13-g.*t2.*t7.*t10.*t14.*t23.*3.0-mu.*sigma.*t11.*t14.*t20.*t24+m_h.*t4.*t7.*t11.*t13.*t19.*2.0+m_h.*t5.*t6.*t11.*t13.*t19.*4.0-t4.*t6.*t11.*t14.*t20.*t24.*4.0-t5.*t7.*t11.*t14.*t20.*t23.*4.0-I_c.*g.*l.*t2.*t7.*t13.*2.0+I_c.*t4.*t7.*t9.*t13.*t19.*4.0+I_c.*t5.*t6.*t9.*t13.*t19-I_c.*g.*l.*m.*m_h.*t2.*t7+I_c.*m.*m_h.*t4.*t7.*t9.*t19.*2.0+I_c.*mu.*sigma.*t9.*t13.*t20.*t24+g.*mu.*sigma.*t2.*t5.*t10.*t14-g.*m_h.*t2.*t7.*t10.*t13.*t23.*2.0-g.*t2.*t4.*t5.*t6.*t10.*t14.*3.0+mu.*sigma.*t4.*t5.*t11.*t14.*t19.*3.0;
    et7 = I_c.*g.*l.*mu.*sigma.*t2.*t5.*t13.*2.0-I_c.*mu.*sigma.*t4.*t5.*t9.*t13.*t19.*3.0+g.*m_h.*mu.*sigma.*t2.*t5.*t10.*t13-g.*mu.*sigma.*t2.*t5.*t10.*t14.*t23.*3.0-g.*m_h.*t2.*t4.*t5.*t6.*t10.*t13.*2.0+m_h.*mu.*sigma.*t4.*t5.*t11.*t13.*t19.*2.0+I_c.*g.*l.*m.*m_h.*mu.*sigma.*t2.*t5-I_c.*m.*m_h.*mu.*sigma.*t4.*t5.*t9.*t19.*2.0-g.*m_h.*mu.*sigma.*t2.*t5.*t10.*t13.*t23.*2.0+g.*mu.*sigma.*t2.*t4.*t6.*t7.*t10.*t14.*3.0+g.*m_h.*mu.*sigma.*t2.*t4.*t6.*t7.*t10.*t13.*2.0;
    theta2_ddot = t82.*(et6+et7).*2.0;
end
if nargout > 3
    et8 = g.*t2.*t8.*t13.*1.6e+1+g.*t2.*t8.*t16.*4.0+g.*t2.*t11.*t15.*2.0-g.*t11.*t15.*t50-g.*t11.*t15.*t55-t4.*t12.*t15.*t19.*2.0-t5.*t12.*t15.*t20.*2.0+t12.*t15.*t19.*t33.*2.0+t12.*t15.*t20.*t34.*2.0+I_c.*g.*t2.*t9.*t14.*1.6e+1-I_c.*t4.*t10.*t14.*t19.*2.2e+1+I_c.*t5.*t10.*t14.*t20.*2.0-I_c.*t10.*t14.*t19.*t33.*2.0+I_c.*t10.*t14.*t20.*t34.*6.0+g.*m.*m_h.*t2.*t8.*1.6e+1+g.*m_h.*t2.*t11.*t14.*8.0+l.*m_h.*t5.*t20.*t37+g.*t2.*t11.*t13.*t16.*4.0-l.*t4.*t8.*t13.*t19.*2.4e+1+l.*t5.*t8.*t13.*t20.*8.0-l.*t4.*t8.*t16.*t19.*8.0-m_h.*t4.*t12.*t14.*t19.*1.2e+1+m_h.*t12.*t14.*t20.*t34.*4.0-t4.*t12.*t13.*t16.*t19.*8.0-l.*m.*m_h.*t4.*t8.*t19.*2.8e+1+I_c.*g.*m.*t2.*t9.*t16.*8.0;
    et9 = I_c.*g.*m_h.*t2.*t9.*t13.*2.4e+1-I_c.*m.*t4.*t10.*t16.*t19.*1.6e+1-I_c.*m_h.*t4.*t10.*t13.*t19.*4.0e+1+I_c.*m_h.*t5.*t10.*t13.*t20.*4.0+I_c.*m_h.*t10.*t13.*t20.*t34.*4.0;
    lambda_n = (t82.*(et8+et9))./2.0;
end
end
