function [theta1_ddot,theta2_ddot] = stick_accelerations(theta1,theta2,theta1_dot,theta2_dot,m,m_h,I_c,l,g,alpha)
%STICK_ACCELERATIONS
%    [THETA1_DDOT,THETA2_DDOT] = STICK_ACCELERATIONS(THETA1,THETA2,THETA1_DOT,THETA2_DOT,M,M_H,I_c,L,G,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:36

t2 = alpha+theta1;
t3 = theta1+theta2;
t4 = I_c.^2;
t5 = l.^2;
t6 = l.^3;
t8 = m.^2;
t10 = theta1_dot.^2;
t11 = theta2_dot.^2;
t15 = -theta2;
t7 = t5.^2;
t12 = sin(t2);
t13 = cos(t3);
t14 = sin(t3);
t16 = t2+t3;
t18 = alpha+t15;
t22 = I_c.*m.*t5.*6.0;
t23 = I_c.*m_h.*t5.*4.0;
t17 = t13.^2;
t19 = m.*m_h.*t7.*4.0;
t20 = sin(t18);
t21 = sin(t16);
t24 = t7.*t8.*5.0;
t25 = t7.*t8.*t17.*4.0;
t26 = -t25;
t27 = t4+t19+t22+t23+t24+t26;
t28 = 1.0./t27;
theta1_ddot = t28.*(g.*t6.*t8.*t12.*3.0+t7.*t8.*t11.*t14.*2.0+I_c.*g.*l.*m.*t12.*3.0+I_c.*g.*l.*m_h.*t12.*2.0+I_c.*m.*t5.*t11.*t14.*2.0+g.*m.*m_h.*t6.*t12.*2.0-g.*t6.*t8.*t13.*t20.*2.0-t7.*t8.*t10.*t13.*t14.*4.0);
if nargout > 1
    theta2_ddot = l.*m.*t28.*(I_c.*g.*t20+g.*m.*t5.*t20.*2.0-g.*m.*t5.*t21.*3.0+g.*m_h.*t5.*t20.*2.0-g.*m_h.*t5.*t21.*2.0+m.*t6.*t10.*t14.*1.0e+1+m_h.*t6.*t10.*t14.*8.0-m.*t6.*t11.*sin(t3.*2.0).*2.0+I_c.*l.*t10.*t14.*2.0);
end
end
