function [lambda_n,lambda_t] = stick_forces(theta1,theta2,theta1_dot,theta2_dot,m,m_h,I_c,l,g,alpha)
%STICK_FORCES
%    [LAMBDA_N,LAMBDA_T] = STICK_FORCES(THETA1,THETA2,THETA1_DOT,THETA2_DOT,M,M_H,I_c,L,G,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:36

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(theta1);
t5 = cos(theta2);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = I_c.^2;
t9 = l.^2;
t10 = l.^3;
t12 = l.^5;
t13 = m.^2;
t14 = m.^3;
t15 = m_h.^2;
t16 = theta1.*2.0;
t17 = theta2.*2.0;
t18 = theta1_dot.^2;
t19 = theta2_dot.^2;
t20 = -alpha;
t11 = t9.^2;
t21 = -t17;
t22 = alpha+t16;
t23 = t17+theta1;
t24 = t16+theta2;
t33 = t16+t17;
t35 = I_c.*m.*t9.*6.0;
t36 = I_c.*m_h.*t9.*4.0;
t25 = sin(t22);
t26 = cos(t23);
t27 = cos(t24);
t28 = sin(t23);
t29 = sin(t24);
t30 = alpha+t21;
t31 = cos(t22);
t32 = m.*m_h.*t11.*4.0;
t38 = t17+t22;
t39 = cos(t33);
t40 = t11.*t13.*3.0;
t41 = t20+t33;
t34 = sin(t30);
t37 = cos(t30);
t42 = t11.*t13.*t39.*2.0;
t43 = -t42;
t44 = t8+t32+t35+t36+t40+t43;
t45 = 1.0./t44;
et1 = g.*m.*t2.*t8.*2.0+g.*m_h.*t2.*t8+g.*m_h.*t31.*t35+g.*t2.*t11.*t14.*2.0+g.*t11.*t14.*t31.*(3.0./2.0)-(g.*t11.*t14.*t37)./2.0-t4.*t12.*t14.*t18.*4.0+t12.*t14.*t18.*t26+t12.*t14.*t19.*t27-(g.*t11.*t14.*cos(t38))./2.0-(g.*t11.*t14.*cos(t41))./2.0+I_c.*g.*t2.*t9.*t13.*7.0+I_c.*g.*t2.*t9.*t15.*2.0+I_c.*g.*t9.*t13.*t31.*(9.0./2.0)+I_c.*g.*t9.*t15.*t31.*2.0+(I_c.*g.*t9.*t13.*t37)./2.0-I_c.*t4.*t10.*t13.*t18.*1.7e+1-I_c.*t4.*t10.*t15.*t18.*8.0+I_c.*t5.*t10.*t13.*t19.*3.0-I_c.*t10.*t13.*t18.*t26+I_c.*t10.*t13.*t19.*t27.*3.0+g.*m.*t2.*t11.*t15.*2.0+g.*m.*t11.*t15.*t31.*2.0+g.*m_h.*t2.*t11.*t13.*5.0+g.*m_h.*t11.*t13.*t31.*4.0-l.*m.*t4.*t8.*t18.*3.0+l.*m.*t5.*t8.*t19;
et2 = l.*m_h.*t4.*t8.*t18.*-2.0-m.*t4.*t12.*t15.*t18.*8.0-m_h.*t4.*t12.*t13.*t18.*1.4e+1+m_h.*t5.*t12.*t13.*t19.*2.0+m_h.*t12.*t13.*t19.*t27.*2.0+I_c.*g.*m.*m_h.*t2.*t9.*8.0-I_c.*m.*m_h.*t4.*t10.*t18.*2.4e+1+I_c.*m.*m_h.*t5.*t10.*t19.*2.0+I_c.*m.*m_h.*t10.*t19.*t27.*2.0;
lambda_n = t45.*(et1+et2);
if nargout > 1
    et3 = g.*m.*t3.*t8.*2.0+g.*m_h.*t3.*t8+g.*t3.*t11.*t14.*2.0-g.*t11.*t14.*t25.*(3.0./2.0)+(g.*t11.*t14.*t34)./2.0+t6.*t12.*t14.*t18.*4.0+t12.*t14.*t18.*t28-t12.*t14.*t19.*t29-(g.*t11.*t14.*sin(t38))./2.0+(g.*t11.*t14.*sin(t41))./2.0+I_c.*g.*t3.*t9.*t13.*7.0+I_c.*g.*t3.*t9.*t15.*2.0-I_c.*g.*t9.*t13.*t25.*(9.0./2.0)-I_c.*g.*t9.*t15.*t25.*2.0-(I_c.*g.*t9.*t13.*t34)./2.0+I_c.*t6.*t10.*t13.*t18.*1.7e+1+I_c.*t6.*t10.*t15.*t18.*8.0+I_c.*t7.*t10.*t13.*t19.*3.0-I_c.*t10.*t13.*t18.*t28-I_c.*t10.*t13.*t19.*t29.*3.0+g.*m.*t3.*t11.*t15.*2.0-g.*m.*t11.*t15.*t25.*2.0+g.*m_h.*t3.*t11.*t13.*5.0-g.*m_h.*t11.*t13.*t25.*4.0+l.*m.*t6.*t8.*t18.*3.0+l.*m.*t7.*t8.*t19;
    et4 = l.*m_h.*t6.*t8.*t18.*2.0+m.*t6.*t12.*t15.*t18.*8.0+m_h.*t6.*t12.*t13.*t18.*1.4e+1+m_h.*t7.*t12.*t13.*t19.*2.0-m_h.*t12.*t13.*t19.*t29.*2.0+I_c.*g.*m.*m_h.*t3.*t9.*8.0-I_c.*g.*m.*m_h.*t9.*t25.*6.0+I_c.*m.*m_h.*t6.*t10.*t18.*2.4e+1+I_c.*m.*m_h.*t7.*t10.*t19.*2.0-I_c.*m.*m_h.*t10.*t19.*t29.*2.0;
    lambda_t = -t45.*(et3+et4);
end
end
