function W_tilde = swing_foot_jacobian(theta1,theta2,l)
%SWING_FOOT_JACOBIAN
%    W_tilde = SWING_FOOT_JACOBIAN(THETA1,THETA2,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:34

W_tilde = reshape([1.0,0.0,0.0,1.0,l.*cos(theta1).*2.0,l.*sin(theta1).*-2.0,l.*cos(theta2).*2.0,l.*sin(theta2).*2.0],[2,4]);
end
