function [x_swing,y_swing] = swing_foot_position(x,y,theta1,theta2,l)
%SWING_FOOT_POSITION
%    [X_SWING,Y_SWING] = SWING_FOOT_POSITION(X,Y,THETA1,THETA2,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    31-Jan-2026 15:11:34

x_swing = x+l.*sin(theta1).*2.0+l.*sin(theta2).*2.0;
if nargout > 1
    y_swing = y+l.*cos(theta1).*2.0-l.*cos(theta2).*2.0;
end
end
