function [LHS_Matrix,RHS_Vector] = get_dynamics_matrices(in1,in2,m1,m2,J1,J2,b,d,k,c,cw,ddpsi)
%GET_DYNAMICS_MATRICES
%    [LHS_Matrix,RHS_Vector] = GET_DYNAMICS_MATRICES(IN1,IN2,M1,M2,J1,J2,B,D,K,C,CW,DDPSI)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Dec-2025 13:24:47

dphi1 = in2(4,:);
dphi2 = in2(5,:);
dtheta = in2(3,:);
dx = in2(1,:);
dy = in2(2,:);
phi1 = in1(4,:);
phi2 = in1(5,:);
theta = in1(3,:);
t2 = cos(phi1);
t3 = cos(phi2);
t4 = J2.*ddpsi;
t5 = m1+m2;
t6 = phi1+theta;
t7 = phi2+theta;
t8 = d.^2;
t15 = -d;
t9 = b.*t2;
t10 = b.*t3;
t11 = cos(t6);
t12 = cos(t7);
t13 = sin(t6);
t14 = sin(t7);
LHS_Matrix = reshape([t5,0.0,0.0,0.0,0.0,0.0,-t13,-t14,0.0,t5,0.0,0.0,0.0,0.0,t11,t12,0.0,0.0,J1+J2,0.0,0.0,J2,-t9+t15,t10+t15,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,t13,-t11,d+t9,d,0.0,0.0,0.0,0.0,t14,-t12,d-t10,0.0,d,0.0,0.0,0.0],[8,8]);
if nargout > 1
    t16 = -t4;
    t17 = cw.*dtheta.*t8;
    t18 = -t17;
    mt1 = [-cw.*(dx.*2.0+d.*dphi1.*t13+d.*dphi2.*t14+d.*dtheta.*t13+d.*dtheta.*t14);cw.*(dy.*-2.0+d.*dphi1.*t11+d.*dphi2.*t12+d.*dtheta.*t11+d.*dtheta.*t12);t16-cw.*(dphi1.*t8+dphi2.*t8+dtheta.*t8.*2.0+b.^2.*dtheta.*2.0+d.*dphi1.*t9+d.*dtheta.*t9.*2.0-d.*dtheta.*t10.*2.0+d.*dx.*t13+d.*dx.*t14+dphi2.*t10.*t15+dy.*t11.*t15+dy.*t12.*t15);t18-c.*dphi1-k.*phi1-cw.*dphi1.*t8+cw.*dtheta.*t9.*t15+cw.*dx.*t13.*t15+cw.*d.*dy.*t11;t18-c.*dphi2-k.*phi2-cw.*dphi2.*t8+cw.*dx.*t14.*t15+cw.*d.*dtheta.*t10+cw.*d.*dy.*t12;t16;dx.*(dphi1.*t11+dtheta.*t11)+dy.*(dphi1.*t13+dtheta.*t13)-b.*dphi1.*dtheta.*sin(phi1)];
    mt2 = [dx.*(dphi2.*t12+dtheta.*t12)+dy.*(dphi2.*t14+dtheta.*t14)+b.*dphi2.*dtheta.*sin(phi2)];
    RHS_Vector = [mt1;mt2];
end
end
