function [LHS_Matrix,RHS_Vector,F_ext_total,M_ext_total] = get_EOM_matrices(in1,in2,m1,m2,J1,J2,b,d,k,c,cw,ddpsi,tau_psi,lambda1,lambda2)
%get_EOM_matrices
%    [LHS_Matrix,RHS_Vector,F_ext_total,M_ext_total] = get_EOM_matrices(IN1,IN2,M1,M2,J1,J2,B,D,K,C,CW,DDPSI,TAU_PSI,LAMBDA1,LAMBDA2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 15:34:32

dphi1 = in2(4,:);
dphi2 = in2(5,:);
dtheta = in2(3,:);
dx = in2(1,:);
dy = in2(2,:);
phi1 = in1(4,:);
phi2 = in1(5,:);
theta = in1(3,:);
t2 = cos(phi1);
t3 = cos(phi2);
t4 = J2.*ddpsi;
t5 = m1+m2;
t6 = phi1+theta;
t7 = phi2+theta;
t8 = b.^2;
t9 = d.^2;
t16 = -d;
t10 = b.*t2;
t11 = b.*t3;
t12 = cos(t6);
t13 = cos(t7);
t14 = sin(t6);
t15 = sin(t7);
LHS_Matrix = reshape([t5,0.0,0.0,0.0,0.0,0.0,-t14,-t15,0.0,t5,0.0,0.0,0.0,0.0,t12,t13,0.0,0.0,J1+J2,0.0,0.0,J2,-t10+t16,t11+t16,0.0,0.0,0.0,0.0,0.0,0.0,t16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t16,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,t14,-t12,d+t10,d,0.0,0.0,0.0,0.0,t15,-t13,d-t11,0.0,d,0.0,0.0,0.0],[8,8]);
if nargout > 1
    t17 = -t4;
    t18 = cw.*dphi1.*t9;
    t19 = cw.*dphi2.*t9;
    t20 = cw.*dtheta.*t9;
    t21 = cw.*d.*dy.*t12;
    t22 = cw.*d.*dy.*t13;
    t25 = -t18;
    t26 = -t19;
    t27 = -t20;
    t28 = cw.*dx.*t14.*t16;
    t29 = cw.*dx.*t15.*t16;
    RHS_Vector = [-cw.*(dx.*2.0+d.*dphi1.*t14+d.*dphi2.*t15+d.*dtheta.*t14+d.*dtheta.*t15);cw.*(dy.*-2.0+d.*dphi1.*t12+d.*dphi2.*t13+d.*dtheta.*t12+d.*dtheta.*t13);t17-cw.*(dphi1.*t9+dphi2.*t9+dtheta.*t8.*2.0+dtheta.*t9.*2.0+d.*dphi1.*t10+d.*dtheta.*t10.*2.0-d.*dtheta.*t11.*2.0+d.*dx.*t14+d.*dx.*t15+dphi2.*t11.*t16+dy.*t12.*t16+dy.*t13.*t16);t21+t25+t27+t28-c.*dphi1-k.*phi1+cw.*dtheta.*t10.*t16;t22+t26+t27+t29-c.*dphi2-k.*phi2+cw.*d.*dtheta.*t11;t17;dx.*(dphi1.*t12+dtheta.*t12)+dy.*(dphi1.*t14+dtheta.*t14)-b.*dphi1.*dtheta.*sin(phi1);dx.*(dphi2.*t13+dtheta.*t13)+dy.*(dphi2.*t15+dtheta.*t15)+b.*dphi2.*dtheta.*sin(phi2)];
end
if nargout > 2
    F_ext_total = [cw.*dx.*-2.0-lambda1.*t14-lambda2.*t15+cw.*dphi1.*t14.*t16+cw.*dphi2.*t15.*t16+cw.*dtheta.*t14.*t16+cw.*dtheta.*t15.*t16;cw.*dy.*-2.0+lambda1.*t12+lambda2.*t13+cw.*d.*dphi1.*t12+cw.*d.*dphi2.*t13+cw.*d.*dtheta.*t12+cw.*d.*dtheta.*t13];
end
if nargout > 3
    M_ext_total = t20.*-2.0+t21+t22+t25+t26+t28+t29-lambda1.*t10+lambda2.*t11+lambda1.*t16+lambda2.*t16-cw.*dtheta.*t8.*2.0+cw.*dphi1.*t10.*t16+cw.*d.*dphi2.*t11-cw.*d.*dtheta.*t10.*2.0+cw.*d.*dtheta.*t11.*2.0;
end
end
