function [F_ext_total,M_ext_total] = get_contact_forces(in1,in2,m1,m2,J1,J2,b,d,k,c,cw,lambda1,lambda2)
%GET_CONTACT_FORCES
%    [F_ext_total,M_ext_total] = GET_CONTACT_FORCES(IN1,IN2,M1,M2,J1,J2,B,D,K,C,CW,LAMBDA1,LAMBDA2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    09-Dec-2025 13:24:48

dphi1 = in2(4,:);
dphi2 = in2(5,:);
dtheta = in2(3,:);
dx = in2(1,:);
dy = in2(2,:);
phi1 = in1(4,:);
phi2 = in1(5,:);
theta = in1(3,:);
t2 = cos(phi1);
t3 = cos(phi2);
t4 = phi1+theta;
t5 = phi2+theta;
t6 = d.^2;
t7 = cos(t4);
t8 = cos(t5);
t9 = sin(t4);
t10 = sin(t5);
F_ext_total = [cw.*dx.*-2.0-lambda1.*t9-lambda2.*t10-cw.*d.*dphi1.*t9-cw.*d.*dphi2.*t10-cw.*d.*dtheta.*t9-cw.*d.*dtheta.*t10;cw.*dy.*-2.0+lambda1.*t7+lambda2.*t8+cw.*d.*dphi1.*t7+cw.*d.*dphi2.*t8+cw.*d.*dtheta.*t7+cw.*d.*dtheta.*t8];
if nargout > 1
    M_ext_total = -d.*lambda1-d.*lambda2-cw.*dphi1.*t6-cw.*dphi2.*t6-cw.*dtheta.*t6.*2.0-b.*lambda1.*t2+b.*lambda2.*t3-b.^2.*cw.*dtheta.*2.0-cw.*d.*dx.*t9-cw.*d.*dx.*t10+cw.*d.*dy.*t7+cw.*d.*dy.*t8-b.*cw.*d.*dphi1.*t2+b.*cw.*d.*dphi2.*t3-b.*cw.*d.*dtheta.*t2.*2.0+b.*cw.*d.*dtheta.*t3.*2.0;
end
end
